language: node_js
git:
  quiet: true
  depth: 3
node_js:
- '8.10'
python:
- "3.6"
cache:
  directories:
  - node_modules
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: A9LtI/8UXdK3jCeVyoSkDfyVWwLTtXmNqgUmUC1aOekDArSceaw2f4NKn5O7XVpi8fgXVs+z+7nQa8L3eMRpBHdYLz6raSAMAIh/gU5PaMFYJk8NUgutrnSmUCG1jRDjM4y/ySHURD60EsGT2t6FhOp/Ct28I4T3bNPSLtRLNMSWp5vAkwuHUTRWrIT4THwHZXJQNe0+932TxR+Olcip1JRO0sL+KucPDZQtXeOIA9Ky8Pfx8DNfOPY3RFHLCgW5PXI8c+C3lI3g0H+khRABIk9MjB4hRFYxGQA5gQgMjnDwm2yDTbXvZ/vkzRcnk7yxNU6NfWF6B09Bf2xcdfxndB3e4ir0RZUONaRfAvurBK1KqUD7ViKUY04O6xcYlzlIOHn08W6UfosP8+eAiW/WtrP/vNS6n7Ntldn0nuPqxO/senfIQUFVkkAyJGAJ9/ux/bb2L0tZxqg+PXnMJhFyUxLAfhS8kh1jXsOXTMmakg0UY+Wy+H5addyWPCOZBki6J9iKRkaTZfiBWMq4AUI1waFyctbvwTla2yPEvtltXWxPwm5Tm3yPf4PhXjcj7vF5tbhjcajqucJxGk+lwFtJC5gNN94kBTzxcZYPAdYWpBJLfB5jFAI4Prjng6IDA4D+MVhCe+iJfEZElPJheeg5ONzmYdMhunSGI4gO0goMhAY=
  - secure: mEYA3Gz9wN2nADkElcX7DtTN3BqBXo4+AQJvaIwlFVqmP4COrtoHw/VzdqA5482k0+xbbFmEfsE6dYz9DfMrlstrh96DS/ZhfrVcG8XerJIrFsyX0QWXFGTUPDRd/5403zmixcmbqy0PYlLej7MlOWKZwPlEbOn+R8l9tFvJ67eFCQi3jyl5cEOhND7Rfd0dnG0U6/5CsTTujyTSluQ+kMCen6OwEdsdGOqf8GR7gRUNeyuSGUrZVhCrD63S1TsQ08oLuJzAFWi/9uscugnO/ef4C4nOQnJ2WJLpBGRsUDnMnfOlkNDoJlo5OOUZA7+7b+Io9BW0mR99tfgZrHf4YVhjv6RWYv4mbCiGdi+Nuc3AZZWU5NegEAnEcrXWuJiooxQW3Ug8vKIl5EYyqkigPQ67Q8EmZy9U7eERRJpkHhcwNqToFsAiqPqmfI6sgb6V8ZXdMpgbqWY6uTi/qHB2HIxC+ApyLGOngqDQQ1jYRRNLY5k6+4trLR/9kw8GB6L1Pq9lFcFgE7be6UhVvLBAqzDCTGnUfIS1F4bulMD4JeHyr7ye92zQbM4ofsouBkRF7wEi2HfsnnAjO01GtHdcy5fpTmN+95AUKfoJjHWWCRdeVqwKz3O5Z8/G2FNYm+f5JAfdHAvlanLNIfm0VXswg6a74aNATGFZ+852ndm+uPk=
branches:
  only:
  - master
before_install:
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - make build
  - make test
after_success: make deploy
notifications:
  slack:
    rooms:
    - secure: gwXsoHavEO2mjfGlG50T1QrMUxJLRh76cdvesvPVbwA8Vch2Ve6q/0CldYIzGWPaDDt+kyndjUInjCVbLEOvSufeAetyIro7T6pu4TU/1LKBFp5VXZwx0bBsAjyevbqE31YuRcY/B2yKdj6NEuIAGqIMAuwRi6cyYiwZuzfHnkdJ5AneqhBu/IgvRsL8fdObD1No6o/vgUYjUZjgHPpxNY2JHu19shr6E/LPyWm7mGwsxEqQR3b85zdMwJCGyZw/CYCC9gT/tg8RqLMUQYv1cWXe0p5HdB6KZBa98+VD4s1zJKB5buxXuwc/bioM4WJ31KAl7Xbv4fdw4YDrn97iGm4brDUGslsRa9p/5jFIYncHT2TsOZyFChVsttZfsPaNq5cKmEaHci5O4jTjR6MKHZePWfh9VWQosfxvOhxyVBwh0Sptz3BJXoFaw26E+9l+x6z/xmVQoE2GR0R5bUSlPG6ChGC+sMH57lxO8RrjDMYmcjEfTfeZUNHR3rHOBY74m4Favsfy9vi0pshSDW31ds19MzOo8q3zpynIPaySYYW1QrzlBvzP3b1muAwaqjTjtOIlEn/6+/7cn/3ymoRU1S9L9xPdleeDuVSThqOvq3zi18Leaa+LAVAU5Kjel8NPqYy/C+xLcV8P/irmrENTGhQHiUYZ7Xq7uyq6Aw0N3Fs=
    template:
    - " `%{result}` <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) in
      *%{duration}* "
    - " Repo: %{repository_slug} @ *%{branch}*"
    - " by *%{author}* "
