language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAILJJKURL5KF2EKTA
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_SECRET_ACCESS_KEY
  - secure: A9LtI/8UXdK3jCeVyoSkDfyVWwLTtXmNqgUmUC1aOekDArSceaw2f4NKn5O7XVpi8fgXVs+z+7nQa8L3eMRpBHdYLz6raSAMAIh/gU5PaMFYJk8NUgutrnSmUCG1jRDjM4y/ySHURD60EsGT2t6FhOp/Ct28I4T3bNPSLtRLNMSWp5vAkwuHUTRWrIT4THwHZXJQNe0+932TxR+Olcip1JRO0sL+KucPDZQtXeOIA9Ky8Pfx8DNfOPY3RFHLCgW5PXI8c+C3lI3g0H+khRABIk9MjB4hRFYxGQA5gQgMjnDwm2yDTbXvZ/vkzRcnk7yxNU6NfWF6B09Bf2xcdfxndB3e4ir0RZUONaRfAvurBK1KqUD7ViKUY04O6xcYlzlIOHn08W6UfosP8+eAiW/WtrP/vNS6n7Ntldn0nuPqxO/senfIQUFVkkAyJGAJ9/ux/bb2L0tZxqg+PXnMJhFyUxLAfhS8kh1jXsOXTMmakg0UY+Wy+H5addyWPCOZBki6J9iKRkaTZfiBWMq4AUI1waFyctbvwTla2yPEvtltXWxPwm5Tm3yPf4PhXjcj7vF5tbhjcajqucJxGk+lwFtJC5gNN94kBTzxcZYPAdYWpBJLfB5jFAI4Prjng6IDA4D+MVhCe+iJfEZElPJheeg5ONzmYdMhunSGI4gO0goMhAY=
  - CHANNEL_ACCESS_TOKEN
  - secure: Wd/F+53PSHSLql+z1+8+qUt44tZZg+40zDSKffYTGPY21s+39Xlck73CZWz13gyZT6MK/LFFDWkiIdcQ/BBMYuiDRSkr/5+PFs40iWu0lBQuNHmXufiYPNPHfTL+SHgctD9KO0F0Vo6BJeeBG1L7R3EKSFKkw55QFwZAY0GVm3Vr3PiS2mgdtmp3J7K2CfLedyfqpSLdqit3De0y53xJVepFrLfTTK0+2IzDOt62qn0mrzk92aA/G5ovTfhmy/HC/Sc/Qq4qw+KgxWcOFa+RwQ5jUXQT67v+SiH2WfO0t9jkggOE0txjBGKPXMJ0ihYB9qK1OwJnvABke0miTefPz3lTEphQVN8WiFVq6amx41b2J1RjAIlGj3jhtlroNUkpdmUkNeWShe+PLvbmdG6aueMPhy1/62M318vA+diAyb7VtptiVbWJHzlZrUNcBMTARHKkV/mh/fGDjZxUJx1Gf0VktTBzX28u6JRkcve3yeNwILDHiDQGyXV2msVdoFsaZ/adcbnToBvebjJvUQGHQ0z+avE8+oaZJAkv87YPiBwcjbIUUk/F4Fge3DkQivma0SZphLQOcAQF5YAwBJqRdEblHonwkenxtNr4Bhn+2BiyvvwFT+EdLJS795EyK/FhsMgUQZWqQGweuiVoNt5+2JsxU4lggiQbMp/3Gf1RP9o=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
