language: node_js
node_js:
- '6.10'
cache: npm
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAILJJKURL5KF2EKTA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: A9LtI/8UXdK3jCeVyoSkDfyVWwLTtXmNqgUmUC1aOekDArSceaw2f4NKn5O7XVpi8fgXVs+z+7nQa8L3eMRpBHdYLz6raSAMAIh/gU5PaMFYJk8NUgutrnSmUCG1jRDjM4y/ySHURD60EsGT2t6FhOp/Ct28I4T3bNPSLtRLNMSWp5vAkwuHUTRWrIT4THwHZXJQNe0+932TxR+Olcip1JRO0sL+KucPDZQtXeOIA9Ky8Pfx8DNfOPY3RFHLCgW5PXI8c+C3lI3g0H+khRABIk9MjB4hRFYxGQA5gQgMjnDwm2yDTbXvZ/vkzRcnk7yxNU6NfWF6B09Bf2xcdfxndB3e4ir0RZUONaRfAvurBK1KqUD7ViKUY04O6xcYlzlIOHn08W6UfosP8+eAiW/WtrP/vNS6n7Ntldn0nuPqxO/senfIQUFVkkAyJGAJ9/ux/bb2L0tZxqg+PXnMJhFyUxLAfhS8kh1jXsOXTMmakg0UY+Wy+H5addyWPCOZBki6J9iKRkaTZfiBWMq4AUI1waFyctbvwTla2yPEvtltXWxPwm5Tm3yPf4PhXjcj7vF5tbhjcajqucJxGk+lwFtJC5gNN94kBTzxcZYPAdYWpBJLfB5jFAI4Prjng6IDA4D+MVhCe+iJfEZElPJheeg5ONzmYdMhunSGI4gO0goMhAY=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make all
notifications:
  slack:
    secure: kHvZIwGhXiKz0jAP546WcvDGAlmE4vHQFfjhb/5H+NUrR7NhT6VoWz77f3nj0icflpkXNCywxHVVlb4nPqYrSQU52CxE9a3p/DIbuCRcmO4Voe0IP3dJ7B1esVb6XbG6TLQVTEkoRLbyCNFOMtqPcdIw8F7O08n1UbcuUh6vv4wQqguqLjU6tcSz2hmnqIC4wLN4WpV8EFJB22pnCmF8DaLV3zB8BkgQkaWe01as85lyFCMfds5MO0OBsfN2z11X9TvpWUoEGvi7aA5cpwMWky8EFp9eFX+poj9COwev+fUxonuPL+pP8CQ8ujNm/AoZrECADjVGLB+Bn0/B33cK5GE84AGcfkJoabQGWzVbUHOLWM6Ht5LKPXNQVu7jUU7vtCnAyebuP1aqEOMrZ2aX0wi/bRwH4yqBadg7JcN38nSsFu8Ov8hIULPbLTfCSh8HjgEHPOq7TorfOIv+daY3X+cF6BaJcYlepc9hfTYOyRkQbybheh1XvTPpHBlDnJ6HI0gN/v7GDY/AtZKFNXl6l+1NCXX+ifdbcBHxlljjZNvV0MwmgekGF+3GeJ8F4XAiOINgcwvZOFH+sEg+7UZAWW2lfxAkYyOU7/cL3Z5sXW6Vmru3N5J7GCfkcOwzv6h6PQqojCKKJacBDb3zJOP/nfTHJwnLggHpE2In6/ggNcI=
